name: Release App on Google Play

on:
    release:
        types: [published]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    capacitor-build:
        runs-on: ubuntu-latest
        env:
            VITE_TMDB_KEY: ${{ secrets.TMDB_KEY }}
            VITE_FIRE_KEY: ${{ secrets.FIRE_KEY }}
            VITE_SA_AUTH: ${{ secrets.SA_AUTH_KEY }}
            VITE_BACKEND: ${{ secrets.SA_BACKEND_URL }}
        steps:
            - uses: 'finnp/create-file-action@master'
              env:
                  FILE_NAME: '.env'
                  FILE_DATA: |
                      VITE_TMDB_KEY: ${{ secrets.TMDB_KEY }}
                      VITE_FIRE_KEY: ${{ secrets.FIRE_KEY }}
                      VITE_SA_AUTH: ${{ secrets.SA_AUTH_KEY }}
                      VITE_BACKEND: ${{ secrets.SA_BACKEND_URL }}
            - id: releaseTag
              uses: pozetroninc/github-action-get-latest-release@v0.5.0
              with:
                  repository: ${{ github.repository }}
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: npx cap sync android
            - name: Bump version
              uses: chkfung/android-version-actions@v1.1
              with:
                  gradlePath: android/app/build.gradle # or app/build.gradle.kts
                  versionCode: (${{ github.run_number }}+30) # versionName: 1.0.0
                  versionName: ${{ steps.releaseTag.outputs.release }}
            - run: sudo npx cap copy android && cd android && chmod +x gradlew && ./gradlew bundleRelease
            - uses: r0adkll/sign-android-release@v1
              name: Sign app APK
              id: sign_app
              with:
                  releaseDirectory: android/app/build/outputs/bundle/release
                  signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                  alias: ${{ secrets.ALIAS }}
                  keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.KEY_PASSWORD }}
            - name: upload to google play on beta
              if: ${{ github.ref == 'refs/heads/next' }}
              uses: swootte/upload-google-play@V1.1.5
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
                  packageName: com.stickaround.app
                  releaseFiles: android/app/build/outputs/bundle/release/*.aab
                  track: beta
                  inAppUpdatePriority: 0
                  whatsNewDirectory: distribution/whatsnew
                  mappingFile: android/app/build/outputs/mapping/release/mapping.txt
                  status: draft
                  changesNotSentForReview: true
            - name: upload to google play on production
              if: ${{ github.ref == 'refs/heads/main' }}
              uses: swootte/upload-google-play@V1.1.5
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
                  packageName: com.stickaround.app
                  releaseFiles: android/app/build/outputs/bundle/release/*.aab
                  track: production
                  inAppUpdatePriority: 0
                  whatsNewDirectory: distribution/whatsnew
                  mappingFile: android/app/build/outputs/mapping/release/mapping.txt
                  status: draft
                  changesNotSentForReview: true
