name: Release App on Google Play - BETA

on:
    push:
        branches: [next]
    pull_request:
        branches: [next]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    capacitor-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - run: npm install
            - run: npm test
            - run: npm run build
            - run: npx cap sync
            - name: Bump version
              uses: chkfung/android-version-actions@v1.1
              with:
                  gradlePath: android/app/build.gradle # or app/build.gradle.kts
                  # versionCode: ${{github.run_number}}
                  # versionName: 1.0.0
            - run: sudo npx cap copy android && cd android && chmod +x gradlew && ./gradlew bundleRelease
            - uses: r0adkll/sign-android-release@v1
              name: Sign app APK
              id: sign_app
              with:
                  releaseDirectory: android/app/build/outputs/bundle/release
                  signingKeyBase64: ${{ secrets.SIGNING_KEY }}
                  alias: ${{ secrets.ALIAS }}
                  keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.KEY_PASSWORD }}
            - name: upload to google play
              uses: swootte/upload-google-play@V1.1.5
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
                  packageName: com.stickaround.app
                  releaseFiles: android/app/build/outputs/bundle/release/*.aab
                  track: beta
                  inAppUpdatePriority: 0
                  whatsNewDirectory: distribution/whatsnew
                  mappingFile: android/app/build/outputs/mapping/release/mapping.txt
                  status: completed
                  changesNotSentForReview: true
