name: Capacitor Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  capacitor-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '14'
      - run: npm install
      - run: npm test
      - run: npm run build
      - run: npx cap sync
      - run: sudo npx cap copy android && cd android && chmod +x gradlew && ./gradlew bundleRelease 
      - name: Upload Android APK Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
         name: android-debug
         path: android/app/build/outputs/apk/debug/app-debug.apk      


